# Generated by Django 6.0.3 on 2026-04-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPINTR_FINALS_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
            ],
        ),
    ]
